spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:matzip-test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:

github:
  client:
    id: github_client_id
    secret: github_client_secret
  url:
    access-token: http://localhost:8180/login/oauth/access_token
    profile: http://localhost:8180/user

server:
  port: 8180
