spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  profiles:
    include: auth,prod
  lifecycle:
    timeout-per-shutdown-phase: 15s
server:
  port: 8080
  shutdown: graceful

